### ISSUE TITLE
BSOD on fresh Windows 7 x64 target VMs

### ISSUE THREAD

**Issue by analyst321** [tetrane/reven-community#11]
**Describe the bug**
Booting windows 7 x64 VMs fails, the VM encounters a BSOD as soon as the windows bootup logo appears. Tried with fresh windows 7 x64 qcow2 images. Tried following 4 variations, with the same results.

- Windows 7 x64 SP0 qcow2 image on the provided docker image on Ubuntu 20.04
- Windows 7 x64 SP1 qcow2 image on the provided docker image on Ubuntu 20.04
- Windows 7 x64 SP0 qcow2 image on Fresh install of Debian Buster on a Physical system
- Windows 7 x64 SP1 qcow2 image on Fresh install of Debian Buster on a Physical system

**To Reproduce**
1- Upload a Windows 7 x64 qcow2 Image
2- Press register VM
3- Start VM, the UI opens up in a browser popup. BSOD occurs as soon as the windows bootup logo is reached, and the VM reboots.

**Expected behavior**
Should be able to boot into the VM without a BSOD.

**Additional Information**
Those same Windows 7 qcow2 images boot fine in a standalone qemu on the same host OSes i.e. Debian Buster, Ubuntu.

**Comment by Quentin01** [comment]
Hi,

It's possible that creating the qcow2 image on recent hypervisor or up-to-date version of Qemu will lead Windows to install different drivers and things that could lead to a BSOD when being executed in a Qemu 2.9 (the Qemu used by REVEN). That's our current hypothesis as we encountered those kind of issues in the past when doing so but it's possible it's something else.

To be able to assist you we would like more information on how you did create those qcow2 images:
 - Did you follow the [documentation on how to create VM using iso in REVEN](https://doc.tetrane.com/free/latest/Managing-VMs/Adding-VMs/Create-VM-ISO.html)?
 - Were you using Qemu for that? Or another hypervisor supporting qcow2?
 - Whatever hypervisor your were using, could you give us its version?
 - Were you using an UEFI boot when creating them?
 - What configuration did you give to the VM (Number of cores, RAM, etc) during the creation? And how many RAM did you give the VM in REVEN?

Thank you for taking the time to open this issue!

**Comment by analyst321** [comment]
Hi Quentin,

Sorry didn't get a chance to follow up on this during the week. I think your hypothesis might be correct then about driver mismatches with newer qemu. I just setup the provided docker image again and created the win7x64 VM from inside the docker with the installed qemu version and seems to be working now. Thank you!

**Comment by Quentin01** [comment]
Great to hear that you were able to fix your issue. I'm closing this issue.
