### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cirno9-dev** [tetrane/reven-community#19]
**Describe the bug**
I can not run the analyze.

When I Click the "Start REVEN server" button , it shows that REVEN server started but was terminated early.

My OS is Ubuntu, and the kernel version is 4.15.0-041500-generic.

**Host Environment**
- REVEN Version 2.10.1
- REVEN Edition "Free Edition"
- REVEN Package Docker

**Logs**
Start date: 2022-01-08 01:02:38.027604+00:00
Command: reven_backend --port 0 --trace /Reven2/2.10.2/Replays/*** --user-data /Reven2/2.10.2/Scenarios/***/UserData --name test
 operator()():196 WAR OSSI disabled.
 operator()():247 WAR Binary range disabled - fast symbol search will be unavailable. Can't open database with filename '/Reven2/2.10.2/Replays/***/index/ossi_ranges.sqlite'
OS not compatible with the current edition

**Additional context**
Do i have to open the OSSI?

**Comment by bbrodard** [comment]
Hi,
From the logs you sent, your analyzed OS may not be in the Free Edition supported range, namely: Windows 7 (32 or 64-bit) and the Debian 9 Stretch VM provided by Tetrane (https://www.tetrane.com/files/download/vms/stretch_x64.qcow2).
If it is in the range, is it possible for you to provide us with details about the analyzed OS version / source ?

**Comment by Cirno9-dev** [comment]
> Hi, From the logs you sent, your analyzed OS may not be in the Free Edition supported range, namely: Windows 7 (32 or 64-bit) and the Debian 9 Stretch VM provided by Tetrane (https://www.tetrane.com/files/download/vms/stretch_x64.qcow2). If it is in the range, is it possible for you to provide us with details about the analyzed OS version / source ?

I used the QEMU VIRTUAL machine created by Debian-9.13.0-amd64-netinst. iso as the analysis OS. Now I'm trying to use the Qcow2 file you provided. ~~But I did not find the login user name and password on the official website.~~
Thanks for your answer, I have now successfully run.

**Comment by bbrodard** [comment]
Nice to to read you succeeded. Thank you.
